CREATE TABLE IF NOT EXISTS users
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  varchar(50),
    email varchar UNIQUE,
    CONSTRAINT pk_user PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS categories
(
    id   bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(50)                             NOT NULL UNIQUE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS EVENTS
(
    id                       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation               varchar(1000),
    category_id              bigint                                  NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
    confirmed_requests       bigint,
    created_on               timestamp WITHOUT TIME ZONE             NOT NULL,
    description              varchar(1000),
    event_date               timestamp WITHOUT TIME ZONE             NOT NULL,
    initiator_id             bigint                                  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    lat                      float                                   NOT NULL,
    lon                      float                                   NOT NULL,
    paid                     boolean                                 NOT NULL,
    participant_limit        bigint,
    published_on             timestamp WITHOUT TIME ZONE,
    request_moderation       boolean                                 NOT NULL,
    state                    varchar                                 NOT NULL,
    title                    varchar(1000),
    ad_message               varchar(1000),
    ad_moderation            boolean,
    views_cache              bigint,
    confirmed_requests_cache bigint,
    CONSTRAINT pk_events PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS requests
(
    id           bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    event_id     bigint                                  NOT NULL REFERENCES EVENTS (id) ON DELETE CASCADE,
    requester_id bigint                                  NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status       varchar                                 NOT NULL,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS compilations
(
    id       bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned   boolean                                 NOT NULL,
    title    varchar(100),
    event_id bigint REFERENCES EVENTS (id) ON DELETE CASCADE,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS compilation_ev
(
    event_id       bigint,
    compilation_id bigint,
    CONSTRAINT pk_ev
        FOREIGN KEY (event_id) REFERENCES EVENTS (id),
    CONSTRAINT pk_comp
        FOREIGN KEY (compilation_id) REFERENCES compilations (id),
    PRIMARY KEY (event_id,
                 compilation_id)
);