CREATE TABLE IF NOT EXISTS stats
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app       VARCHAR(50)  NOT NULL,
    uri       VARCHAR(255) NOT NULL,
    ip        VARCHAR(45)  NOT NULL,
    timestamp timestamp    NOT NULL
);


